// Code generated by "enumer -type=OpType -output=gen_optype_enumer.go optypes.go"; DO NOT EDIT.

package optypes

import (
	"fmt"
	"strings"
)

const _OpTypeName = "InvalidFuncReturnConstantIdentityAbsAddAllReduceAndAtan2BatchNormInferenceBatchNormTrainingBatchNormGradBitcastConvertBroadcastInDimCallCbrtCeilClampCollectiveBroadcastCompareComplexConcatenateConvertConvolutionCosineCountLeadingZerosDivideDotGeneralDynamicSliceDynamicUpdateSliceErfExponentialExponentialMinusOneFftFloorGatherIfImagIsFiniteIotaLogLogPlusOneLogisticMaximumMinimumMultiplyNegateNotOrPadPopcntPowerRealRemainderReduceReduceWindowReshapeReverseRNGBitGeneratorRoundNearestAfzRoundNearestEvenRsqrtScatterSelectSelectAndScatterShiftLeftShiftRightArithmeticShiftRightLogicalSignSineSliceSortSqrtSubtractTanTanhTransposeWhileXorGetDimensionSizeAllGatherAllToAllCaseCholeskyCollectivePermuteCompositeCustomCallDynamicBroadcastInDimDynamicConvDynamicGatherDynamicIotaDynamicPadDynamicReshapeGetTupleElementInfeedOptimizationBarrierOutfeedPartitionIdRecvReducePrecisionReduceScatterSendTriangularSolveTupleUniformDequantizeUniformQuantizeLast"

var _OpTypeIndex = [...]uint16{0, 7, 17, 25, 33, 36, 39, 48, 51, 56, 74, 91, 104, 118, 132, 136, 140, 144, 149, 168, 175, 182, 193, 200, 211, 217, 234, 240, 250, 262, 280, 283, 294, 313, 316, 321, 327, 329, 333, 341, 345, 348, 358, 366, 373, 380, 388, 394, 397, 399, 402, 408, 413, 417, 426, 432, 444, 451, 458, 473, 488, 504, 509, 516, 522, 538, 547, 567, 584, 588, 592, 597, 601, 605, 613, 616, 620, 629, 634, 637, 653, 662, 670, 674, 682, 699, 708, 718, 739, 750, 763, 774, 784, 798, 813, 819, 838, 845, 856, 860, 875, 888, 892, 907, 912, 929, 944, 948}

const _OpTypeLowerName = "invalidfuncreturnconstantidentityabsaddallreduceandatan2batchnorminferencebatchnormtrainingbatchnormgradbitcastconvertbroadcastindimcallcbrtceilclampcollectivebroadcastcomparecomplexconcatenateconvertconvolutioncosinecountleadingzerosdividedotgeneraldynamicslicedynamicupdatesliceerfexponentialexponentialminusonefftfloorgatherifimagisfiniteiotaloglogplusonelogisticmaximumminimummultiplynegatenotorpadpopcntpowerrealremainderreducereducewindowreshapereverserngbitgeneratorroundnearestafzroundnearestevenrsqrtscatterselectselectandscattershiftleftshiftrightarithmeticshiftrightlogicalsignsineslicesortsqrtsubtracttantanhtransposewhilexorgetdimensionsizeallgatheralltoallcasecholeskycollectivepermutecompositecustomcalldynamicbroadcastindimdynamicconvdynamicgatherdynamiciotadynamicpaddynamicreshapegettupleelementinfeedoptimizationbarrieroutfeedpartitionidrecvreduceprecisionreducescattersendtriangularsolvetupleuniformdequantizeuniformquantizelast"

func (i OpType) String() string {
	if i < 0 || i >= OpType(len(_OpTypeIndex)-1) {
		return fmt.Sprintf("OpType(%d)", i)
	}
	return _OpTypeName[_OpTypeIndex[i]:_OpTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _OpTypeNoOp() {
	var x [1]struct{}
	_ = x[Invalid-(0)]
	_ = x[FuncReturn-(1)]
	_ = x[Constant-(2)]
	_ = x[Identity-(3)]
	_ = x[Abs-(4)]
	_ = x[Add-(5)]
	_ = x[AllReduce-(6)]
	_ = x[And-(7)]
	_ = x[Atan2-(8)]
	_ = x[BatchNormInference-(9)]
	_ = x[BatchNormTraining-(10)]
	_ = x[BatchNormGrad-(11)]
	_ = x[BitcastConvert-(12)]
	_ = x[BroadcastInDim-(13)]
	_ = x[Call-(14)]
	_ = x[Cbrt-(15)]
	_ = x[Ceil-(16)]
	_ = x[Clamp-(17)]
	_ = x[CollectiveBroadcast-(18)]
	_ = x[Compare-(19)]
	_ = x[Complex-(20)]
	_ = x[Concatenate-(21)]
	_ = x[Convert-(22)]
	_ = x[Convolution-(23)]
	_ = x[Cosine-(24)]
	_ = x[CountLeadingZeros-(25)]
	_ = x[Divide-(26)]
	_ = x[DotGeneral-(27)]
	_ = x[DynamicSlice-(28)]
	_ = x[DynamicUpdateSlice-(29)]
	_ = x[Erf-(30)]
	_ = x[Exponential-(31)]
	_ = x[ExponentialMinusOne-(32)]
	_ = x[Fft-(33)]
	_ = x[Floor-(34)]
	_ = x[Gather-(35)]
	_ = x[If-(36)]
	_ = x[Imag-(37)]
	_ = x[IsFinite-(38)]
	_ = x[Iota-(39)]
	_ = x[Log-(40)]
	_ = x[LogPlusOne-(41)]
	_ = x[Logistic-(42)]
	_ = x[Maximum-(43)]
	_ = x[Minimum-(44)]
	_ = x[Multiply-(45)]
	_ = x[Negate-(46)]
	_ = x[Not-(47)]
	_ = x[Or-(48)]
	_ = x[Pad-(49)]
	_ = x[Popcnt-(50)]
	_ = x[Power-(51)]
	_ = x[Real-(52)]
	_ = x[Remainder-(53)]
	_ = x[Reduce-(54)]
	_ = x[ReduceWindow-(55)]
	_ = x[Reshape-(56)]
	_ = x[Reverse-(57)]
	_ = x[RNGBitGenerator-(58)]
	_ = x[RoundNearestAfz-(59)]
	_ = x[RoundNearestEven-(60)]
	_ = x[Rsqrt-(61)]
	_ = x[Scatter-(62)]
	_ = x[Select-(63)]
	_ = x[SelectAndScatter-(64)]
	_ = x[ShiftLeft-(65)]
	_ = x[ShiftRightArithmetic-(66)]
	_ = x[ShiftRightLogical-(67)]
	_ = x[Sign-(68)]
	_ = x[Sine-(69)]
	_ = x[Slice-(70)]
	_ = x[Sort-(71)]
	_ = x[Sqrt-(72)]
	_ = x[Subtract-(73)]
	_ = x[Tan-(74)]
	_ = x[Tanh-(75)]
	_ = x[Transpose-(76)]
	_ = x[While-(77)]
	_ = x[Xor-(78)]
	_ = x[GetDimensionSize-(79)]
	_ = x[AllGather-(80)]
	_ = x[AllToAll-(81)]
	_ = x[Case-(82)]
	_ = x[Cholesky-(83)]
	_ = x[CollectivePermute-(84)]
	_ = x[Composite-(85)]
	_ = x[CustomCall-(86)]
	_ = x[DynamicBroadcastInDim-(87)]
	_ = x[DynamicConv-(88)]
	_ = x[DynamicGather-(89)]
	_ = x[DynamicIota-(90)]
	_ = x[DynamicPad-(91)]
	_ = x[DynamicReshape-(92)]
	_ = x[GetTupleElement-(93)]
	_ = x[Infeed-(94)]
	_ = x[OptimizationBarrier-(95)]
	_ = x[Outfeed-(96)]
	_ = x[PartitionId-(97)]
	_ = x[Recv-(98)]
	_ = x[ReducePrecision-(99)]
	_ = x[ReduceScatter-(100)]
	_ = x[Send-(101)]
	_ = x[TriangularSolve-(102)]
	_ = x[Tuple-(103)]
	_ = x[UniformDequantize-(104)]
	_ = x[UniformQuantize-(105)]
	_ = x[Last-(106)]
}

var _OpTypeValues = []OpType{Invalid, FuncReturn, Constant, Identity, Abs, Add, AllReduce, And, Atan2, BatchNormInference, BatchNormTraining, BatchNormGrad, BitcastConvert, BroadcastInDim, Call, Cbrt, Ceil, Clamp, CollectiveBroadcast, Compare, Complex, Concatenate, Convert, Convolution, Cosine, CountLeadingZeros, Divide, DotGeneral, DynamicSlice, DynamicUpdateSlice, Erf, Exponential, ExponentialMinusOne, Fft, Floor, Gather, If, Imag, IsFinite, Iota, Log, LogPlusOne, Logistic, Maximum, Minimum, Multiply, Negate, Not, Or, Pad, Popcnt, Power, Real, Remainder, Reduce, ReduceWindow, Reshape, Reverse, RNGBitGenerator, RoundNearestAfz, RoundNearestEven, Rsqrt, Scatter, Select, SelectAndScatter, ShiftLeft, ShiftRightArithmetic, ShiftRightLogical, Sign, Sine, Slice, Sort, Sqrt, Subtract, Tan, Tanh, Transpose, While, Xor, GetDimensionSize, AllGather, AllToAll, Case, Cholesky, CollectivePermute, Composite, CustomCall, DynamicBroadcastInDim, DynamicConv, DynamicGather, DynamicIota, DynamicPad, DynamicReshape, GetTupleElement, Infeed, OptimizationBarrier, Outfeed, PartitionId, Recv, ReducePrecision, ReduceScatter, Send, TriangularSolve, Tuple, UniformDequantize, UniformQuantize, Last}

var _OpTypeNameToValueMap = map[string]OpType{
	_OpTypeName[0:7]:          Invalid,
	_OpTypeLowerName[0:7]:     Invalid,
	_OpTypeName[7:17]:         FuncReturn,
	_OpTypeLowerName[7:17]:    FuncReturn,
	_OpTypeName[17:25]:        Constant,
	_OpTypeLowerName[17:25]:   Constant,
	_OpTypeName[25:33]:        Identity,
	_OpTypeLowerName[25:33]:   Identity,
	_OpTypeName[33:36]:        Abs,
	_OpTypeLowerName[33:36]:   Abs,
	_OpTypeName[36:39]:        Add,
	_OpTypeLowerName[36:39]:   Add,
	_OpTypeName[39:48]:        AllReduce,
	_OpTypeLowerName[39:48]:   AllReduce,
	_OpTypeName[48:51]:        And,
	_OpTypeLowerName[48:51]:   And,
	_OpTypeName[51:56]:        Atan2,
	_OpTypeLowerName[51:56]:   Atan2,
	_OpTypeName[56:74]:        BatchNormInference,
	_OpTypeLowerName[56:74]:   BatchNormInference,
	_OpTypeName[74:91]:        BatchNormTraining,
	_OpTypeLowerName[74:91]:   BatchNormTraining,
	_OpTypeName[91:104]:       BatchNormGrad,
	_OpTypeLowerName[91:104]:  BatchNormGrad,
	_OpTypeName[104:118]:      BitcastConvert,
	_OpTypeLowerName[104:118]: BitcastConvert,
	_OpTypeName[118:132]:      BroadcastInDim,
	_OpTypeLowerName[118:132]: BroadcastInDim,
	_OpTypeName[132:136]:      Call,
	_OpTypeLowerName[132:136]: Call,
	_OpTypeName[136:140]:      Cbrt,
	_OpTypeLowerName[136:140]: Cbrt,
	_OpTypeName[140:144]:      Ceil,
	_OpTypeLowerName[140:144]: Ceil,
	_OpTypeName[144:149]:      Clamp,
	_OpTypeLowerName[144:149]: Clamp,
	_OpTypeName[149:168]:      CollectiveBroadcast,
	_OpTypeLowerName[149:168]: CollectiveBroadcast,
	_OpTypeName[168:175]:      Compare,
	_OpTypeLowerName[168:175]: Compare,
	_OpTypeName[175:182]:      Complex,
	_OpTypeLowerName[175:182]: Complex,
	_OpTypeName[182:193]:      Concatenate,
	_OpTypeLowerName[182:193]: Concatenate,
	_OpTypeName[193:200]:      Convert,
	_OpTypeLowerName[193:200]: Convert,
	_OpTypeName[200:211]:      Convolution,
	_OpTypeLowerName[200:211]: Convolution,
	_OpTypeName[211:217]:      Cosine,
	_OpTypeLowerName[211:217]: Cosine,
	_OpTypeName[217:234]:      CountLeadingZeros,
	_OpTypeLowerName[217:234]: CountLeadingZeros,
	_OpTypeName[234:240]:      Divide,
	_OpTypeLowerName[234:240]: Divide,
	_OpTypeName[240:250]:      DotGeneral,
	_OpTypeLowerName[240:250]: DotGeneral,
	_OpTypeName[250:262]:      DynamicSlice,
	_OpTypeLowerName[250:262]: DynamicSlice,
	_OpTypeName[262:280]:      DynamicUpdateSlice,
	_OpTypeLowerName[262:280]: DynamicUpdateSlice,
	_OpTypeName[280:283]:      Erf,
	_OpTypeLowerName[280:283]: Erf,
	_OpTypeName[283:294]:      Exponential,
	_OpTypeLowerName[283:294]: Exponential,
	_OpTypeName[294:313]:      ExponentialMinusOne,
	_OpTypeLowerName[294:313]: ExponentialMinusOne,
	_OpTypeName[313:316]:      Fft,
	_OpTypeLowerName[313:316]: Fft,
	_OpTypeName[316:321]:      Floor,
	_OpTypeLowerName[316:321]: Floor,
	_OpTypeName[321:327]:      Gather,
	_OpTypeLowerName[321:327]: Gather,
	_OpTypeName[327:329]:      If,
	_OpTypeLowerName[327:329]: If,
	_OpTypeName[329:333]:      Imag,
	_OpTypeLowerName[329:333]: Imag,
	_OpTypeName[333:341]:      IsFinite,
	_OpTypeLowerName[333:341]: IsFinite,
	_OpTypeName[341:345]:      Iota,
	_OpTypeLowerName[341:345]: Iota,
	_OpTypeName[345:348]:      Log,
	_OpTypeLowerName[345:348]: Log,
	_OpTypeName[348:358]:      LogPlusOne,
	_OpTypeLowerName[348:358]: LogPlusOne,
	_OpTypeName[358:366]:      Logistic,
	_OpTypeLowerName[358:366]: Logistic,
	_OpTypeName[366:373]:      Maximum,
	_OpTypeLowerName[366:373]: Maximum,
	_OpTypeName[373:380]:      Minimum,
	_OpTypeLowerName[373:380]: Minimum,
	_OpTypeName[380:388]:      Multiply,
	_OpTypeLowerName[380:388]: Multiply,
	_OpTypeName[388:394]:      Negate,
	_OpTypeLowerName[388:394]: Negate,
	_OpTypeName[394:397]:      Not,
	_OpTypeLowerName[394:397]: Not,
	_OpTypeName[397:399]:      Or,
	_OpTypeLowerName[397:399]: Or,
	_OpTypeName[399:402]:      Pad,
	_OpTypeLowerName[399:402]: Pad,
	_OpTypeName[402:408]:      Popcnt,
	_OpTypeLowerName[402:408]: Popcnt,
	_OpTypeName[408:413]:      Power,
	_OpTypeLowerName[408:413]: Power,
	_OpTypeName[413:417]:      Real,
	_OpTypeLowerName[413:417]: Real,
	_OpTypeName[417:426]:      Remainder,
	_OpTypeLowerName[417:426]: Remainder,
	_OpTypeName[426:432]:      Reduce,
	_OpTypeLowerName[426:432]: Reduce,
	_OpTypeName[432:444]:      ReduceWindow,
	_OpTypeLowerName[432:444]: ReduceWindow,
	_OpTypeName[444:451]:      Reshape,
	_OpTypeLowerName[444:451]: Reshape,
	_OpTypeName[451:458]:      Reverse,
	_OpTypeLowerName[451:458]: Reverse,
	_OpTypeName[458:473]:      RNGBitGenerator,
	_OpTypeLowerName[458:473]: RNGBitGenerator,
	_OpTypeName[473:488]:      RoundNearestAfz,
	_OpTypeLowerName[473:488]: RoundNearestAfz,
	_OpTypeName[488:504]:      RoundNearestEven,
	_OpTypeLowerName[488:504]: RoundNearestEven,
	_OpTypeName[504:509]:      Rsqrt,
	_OpTypeLowerName[504:509]: Rsqrt,
	_OpTypeName[509:516]:      Scatter,
	_OpTypeLowerName[509:516]: Scatter,
	_OpTypeName[516:522]:      Select,
	_OpTypeLowerName[516:522]: Select,
	_OpTypeName[522:538]:      SelectAndScatter,
	_OpTypeLowerName[522:538]: SelectAndScatter,
	_OpTypeName[538:547]:      ShiftLeft,
	_OpTypeLowerName[538:547]: ShiftLeft,
	_OpTypeName[547:567]:      ShiftRightArithmetic,
	_OpTypeLowerName[547:567]: ShiftRightArithmetic,
	_OpTypeName[567:584]:      ShiftRightLogical,
	_OpTypeLowerName[567:584]: ShiftRightLogical,
	_OpTypeName[584:588]:      Sign,
	_OpTypeLowerName[584:588]: Sign,
	_OpTypeName[588:592]:      Sine,
	_OpTypeLowerName[588:592]: Sine,
	_OpTypeName[592:597]:      Slice,
	_OpTypeLowerName[592:597]: Slice,
	_OpTypeName[597:601]:      Sort,
	_OpTypeLowerName[597:601]: Sort,
	_OpTypeName[601:605]:      Sqrt,
	_OpTypeLowerName[601:605]: Sqrt,
	_OpTypeName[605:613]:      Subtract,
	_OpTypeLowerName[605:613]: Subtract,
	_OpTypeName[613:616]:      Tan,
	_OpTypeLowerName[613:616]: Tan,
	_OpTypeName[616:620]:      Tanh,
	_OpTypeLowerName[616:620]: Tanh,
	_OpTypeName[620:629]:      Transpose,
	_OpTypeLowerName[620:629]: Transpose,
	_OpTypeName[629:634]:      While,
	_OpTypeLowerName[629:634]: While,
	_OpTypeName[634:637]:      Xor,
	_OpTypeLowerName[634:637]: Xor,
	_OpTypeName[637:653]:      GetDimensionSize,
	_OpTypeLowerName[637:653]: GetDimensionSize,
	_OpTypeName[653:662]:      AllGather,
	_OpTypeLowerName[653:662]: AllGather,
	_OpTypeName[662:670]:      AllToAll,
	_OpTypeLowerName[662:670]: AllToAll,
	_OpTypeName[670:674]:      Case,
	_OpTypeLowerName[670:674]: Case,
	_OpTypeName[674:682]:      Cholesky,
	_OpTypeLowerName[674:682]: Cholesky,
	_OpTypeName[682:699]:      CollectivePermute,
	_OpTypeLowerName[682:699]: CollectivePermute,
	_OpTypeName[699:708]:      Composite,
	_OpTypeLowerName[699:708]: Composite,
	_OpTypeName[708:718]:      CustomCall,
	_OpTypeLowerName[708:718]: CustomCall,
	_OpTypeName[718:739]:      DynamicBroadcastInDim,
	_OpTypeLowerName[718:739]: DynamicBroadcastInDim,
	_OpTypeName[739:750]:      DynamicConv,
	_OpTypeLowerName[739:750]: DynamicConv,
	_OpTypeName[750:763]:      DynamicGather,
	_OpTypeLowerName[750:763]: DynamicGather,
	_OpTypeName[763:774]:      DynamicIota,
	_OpTypeLowerName[763:774]: DynamicIota,
	_OpTypeName[774:784]:      DynamicPad,
	_OpTypeLowerName[774:784]: DynamicPad,
	_OpTypeName[784:798]:      DynamicReshape,
	_OpTypeLowerName[784:798]: DynamicReshape,
	_OpTypeName[798:813]:      GetTupleElement,
	_OpTypeLowerName[798:813]: GetTupleElement,
	_OpTypeName[813:819]:      Infeed,
	_OpTypeLowerName[813:819]: Infeed,
	_OpTypeName[819:838]:      OptimizationBarrier,
	_OpTypeLowerName[819:838]: OptimizationBarrier,
	_OpTypeName[838:845]:      Outfeed,
	_OpTypeLowerName[838:845]: Outfeed,
	_OpTypeName[845:856]:      PartitionId,
	_OpTypeLowerName[845:856]: PartitionId,
	_OpTypeName[856:860]:      Recv,
	_OpTypeLowerName[856:860]: Recv,
	_OpTypeName[860:875]:      ReducePrecision,
	_OpTypeLowerName[860:875]: ReducePrecision,
	_OpTypeName[875:888]:      ReduceScatter,
	_OpTypeLowerName[875:888]: ReduceScatter,
	_OpTypeName[888:892]:      Send,
	_OpTypeLowerName[888:892]: Send,
	_OpTypeName[892:907]:      TriangularSolve,
	_OpTypeLowerName[892:907]: TriangularSolve,
	_OpTypeName[907:912]:      Tuple,
	_OpTypeLowerName[907:912]: Tuple,
	_OpTypeName[912:929]:      UniformDequantize,
	_OpTypeLowerName[912:929]: UniformDequantize,
	_OpTypeName[929:944]:      UniformQuantize,
	_OpTypeLowerName[929:944]: UniformQuantize,
	_OpTypeName[944:948]:      Last,
	_OpTypeLowerName[944:948]: Last,
}

var _OpTypeNames = []string{
	_OpTypeName[0:7],
	_OpTypeName[7:17],
	_OpTypeName[17:25],
	_OpTypeName[25:33],
	_OpTypeName[33:36],
	_OpTypeName[36:39],
	_OpTypeName[39:48],
	_OpTypeName[48:51],
	_OpTypeName[51:56],
	_OpTypeName[56:74],
	_OpTypeName[74:91],
	_OpTypeName[91:104],
	_OpTypeName[104:118],
	_OpTypeName[118:132],
	_OpTypeName[132:136],
	_OpTypeName[136:140],
	_OpTypeName[140:144],
	_OpTypeName[144:149],
	_OpTypeName[149:168],
	_OpTypeName[168:175],
	_OpTypeName[175:182],
	_OpTypeName[182:193],
	_OpTypeName[193:200],
	_OpTypeName[200:211],
	_OpTypeName[211:217],
	_OpTypeName[217:234],
	_OpTypeName[234:240],
	_OpTypeName[240:250],
	_OpTypeName[250:262],
	_OpTypeName[262:280],
	_OpTypeName[280:283],
	_OpTypeName[283:294],
	_OpTypeName[294:313],
	_OpTypeName[313:316],
	_OpTypeName[316:321],
	_OpTypeName[321:327],
	_OpTypeName[327:329],
	_OpTypeName[329:333],
	_OpTypeName[333:341],
	_OpTypeName[341:345],
	_OpTypeName[345:348],
	_OpTypeName[348:358],
	_OpTypeName[358:366],
	_OpTypeName[366:373],
	_OpTypeName[373:380],
	_OpTypeName[380:388],
	_OpTypeName[388:394],
	_OpTypeName[394:397],
	_OpTypeName[397:399],
	_OpTypeName[399:402],
	_OpTypeName[402:408],
	_OpTypeName[408:413],
	_OpTypeName[413:417],
	_OpTypeName[417:426],
	_OpTypeName[426:432],
	_OpTypeName[432:444],
	_OpTypeName[444:451],
	_OpTypeName[451:458],
	_OpTypeName[458:473],
	_OpTypeName[473:488],
	_OpTypeName[488:504],
	_OpTypeName[504:509],
	_OpTypeName[509:516],
	_OpTypeName[516:522],
	_OpTypeName[522:538],
	_OpTypeName[538:547],
	_OpTypeName[547:567],
	_OpTypeName[567:584],
	_OpTypeName[584:588],
	_OpTypeName[588:592],
	_OpTypeName[592:597],
	_OpTypeName[597:601],
	_OpTypeName[601:605],
	_OpTypeName[605:613],
	_OpTypeName[613:616],
	_OpTypeName[616:620],
	_OpTypeName[620:629],
	_OpTypeName[629:634],
	_OpTypeName[634:637],
	_OpTypeName[637:653],
	_OpTypeName[653:662],
	_OpTypeName[662:670],
	_OpTypeName[670:674],
	_OpTypeName[674:682],
	_OpTypeName[682:699],
	_OpTypeName[699:708],
	_OpTypeName[708:718],
	_OpTypeName[718:739],
	_OpTypeName[739:750],
	_OpTypeName[750:763],
	_OpTypeName[763:774],
	_OpTypeName[774:784],
	_OpTypeName[784:798],
	_OpTypeName[798:813],
	_OpTypeName[813:819],
	_OpTypeName[819:838],
	_OpTypeName[838:845],
	_OpTypeName[845:856],
	_OpTypeName[856:860],
	_OpTypeName[860:875],
	_OpTypeName[875:888],
	_OpTypeName[888:892],
	_OpTypeName[892:907],
	_OpTypeName[907:912],
	_OpTypeName[912:929],
	_OpTypeName[929:944],
	_OpTypeName[944:948],
}

// OpTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func OpTypeString(s string) (OpType, error) {
	if val, ok := _OpTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _OpTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to OpType values", s)
}

// OpTypeValues returns all values of the enum
func OpTypeValues() []OpType {
	return _OpTypeValues
}

// OpTypeStrings returns a slice of all String values of the enum
func OpTypeStrings() []string {
	strs := make([]string, len(_OpTypeNames))
	copy(strs, _OpTypeNames)
	return strs
}

// IsAOpType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i OpType) IsAOpType() bool {
	for _, v := range _OpTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
